name: CICD
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: BranchCheckout
        uses: actions/checkout@v1
      - name: ConfigureAWSCredentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
            aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
            aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
            aws-region: us-east-1
      - name: StaticBuild
        run: yarn install && yarn build
      - name: DeployToS3
        run: aws s3 sync ./build/ s3://100daysofcloud-livestream --delete